apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-pod-executor-sa
  namespace: test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-pod-executor
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-pod-executor-binding
subjects:
- kind: ServiceAccount
  name: cluster-pod-executor-sa
  namespace: test
roleRef:
  kind: ClusterRole
  name: cluster-pod-executor
  apiGroup: rbac.authorization.k8s.io