oc delete vm database -n vmimported-user1
oc delete vm winweb01 -n vmimported-user1
oc delete vm winweb02 -n vmimported-user1
oc delete vm database -n vmimported-user10
oc delete vm winweb01 -n vmimported-user10
oc delete vm winweb02 -n vmimported-user10
oc delete vm database -n vmimported-user11
oc delete vm winweb01 -n vmimported-user11
oc delete vm winweb02 -n vmimported-user11
oc delete vm database -n vmimported-user12
oc delete vm winweb01 -n vmimported-user12
oc delete vm winweb02 -n vmimported-user12
oc delete vm database -n vmimported-user13
oc delete vm winweb01 -n vmimported-user13
oc delete vm winweb02 -n vmimported-user13
oc delete vm database -n vmimported-user14
oc delete vm winweb01 -n vmimported-user14
oc delete vm winweb02 -n vmimported-user14
oc delete vm database -n vmimported-user15
oc delete vm winweb01 -n vmimported-user15
oc delete vm winweb02 -n vmimported-user15
oc delete vm database -n vmimported-user16
oc delete vm winweb01 -n vmimported-user16
oc delete vm winweb02 -n vmimported-user16
oc delete vm database -n vmimported-user17
oc delete vm winweb01 -n vmimported-user17
oc delete vm winweb02 -n vmimported-user17
oc delete vm database -n vmimported-user18
oc delete vm winweb01 -n vmimported-user18
oc delete vm winweb02 -n vmimported-user18
oc delete vm database -n vmimported-user19
oc delete vm winweb01 -n vmimported-user19
oc delete vm winweb02 -n vmimported-user19
oc delete vm database -n vmimported-user2
oc delete vm winweb01 -n vmimported-user2
oc delete vm winweb02 -n vmimported-user2
oc delete vm database -n vmimported-user20
oc delete vm winweb01 -n vmimported-user20
oc delete vm winweb02 -n vmimported-user20
oc delete vm database -n vmimported-user3
oc delete vm winweb01 -n vmimported-user3
oc delete vm winweb02 -n vmimported-user3
oc delete vm database -n vmimported-user4
oc delete vm winweb01 -n vmimported-user4
oc delete vm winweb02 -n vmimported-user4
oc delete vm database -n vmimported-user5
oc delete vm winweb01 -n vmimported-user5
oc delete vm winweb02 -n vmimported-user5
oc delete vm database -n vmimported-user6
oc delete vm winweb01 -n vmimported-user6
oc delete vm winweb02 -n vmimported-user6
oc delete vm database -n vmimported-user7
oc delete vm winweb01 -n vmimported-user7
oc delete vm winweb02 -n vmimported-user7
oc delete vm database -n vmimported-user8
oc delete vm winweb01 -n vmimported-user8
oc delete vm winweb02 -n vmimported-user8
oc delete vm database -n vmimported-user9
oc delete vm winweb01 -n vmimported-user9
oc delete vm winweb02 -n vmimported-user9