oc delete dpa oadp-dpa -n oadp-user10
oc delete dpa oadp-dpa -n oadp-user11
oc delete dpa oadp-dpa -n oadp-user12
oc delete dpa oadp-dpa -n oadp-user13
oc delete dpa oadp-dpa -n oadp-user14
oc delete dpa oadp-dpa -n oadp-user15
oc delete dpa oadp-dpa -n oadp-user16
oc delete dpa oadp-dpa -n oadp-user17
oc delete dpa oadp-dpa -n oadp-user18
oc delete dpa oadp-dpa -n oadp-user19
oc delete dpa oadp-dpa -n oadp-user2
oc delete dpa oadp-dpa -n oadp-user20
oc delete dpa oadp-dpa -n oadp-user3
oc delete dpa oadp-dpa -n oadp-user4
oc delete dpa oadp-dpa -n oadp-user5
oc delete dpa oadp-dpa -n oadp-user6
oc delete dpa oadp-dpa -n oadp-user7
oc delete dpa oadp-dpa -n oadp-user8
oc delete dpa oadp-dpa -n oadp-user9
